FROM openjdk:8-jdk

ARG ANDROID_TARGET_SDK="25"
ARG ANDROID_BUILD_TOOLS="24.0.0"
ARG ANDROID_SDK_TOOLS="24.4.1"

ENV ANDROID_COMPILE_SDK ${ANDROID_COMPILE_SDK}
ENV ANDROID_BUILD_TOOLS ${ANDROID_BUILD_TOOLS}
ENV ANDROID_SDK_TOOLS ${ANDROID_SDK_TOOLS}

ADD install.sh /install.sh
RUN /install.sh

ENV ANDROID_HOME /opt/android-sdk-linux
ENV PATH $PATH:/opt/android-sdk-linux/platform-tools/
